name: EAS Build (Test)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create test EAS build
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          registry-url: https://registry.npmjs.org
          scope: "@tendrel"
      - name: Install Dependencies
        env:
          BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun install --frozen-lockfile

      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Prepare bunfig for EAS
        run: bun scripts/prepare-bunfig.ts

      - name: ğŸš€ Build app
        run: eas build --platform all --profile test --non-interactive
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ always() && (needs.build.result == 'failure' || needs.build.result == 'timed_out') }}
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # tendrel-tweets channel
          channel-id: "C041PBUKSJF"
          slack-message: "ğŸš¨ Checklist EAS Build failure ğŸš¨ \n Commit: ${{ github.sha }} \n https://expo.dev/accounts/tendrel/projects/checklist/builds"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
