name: EAS Build (Test)

on:
  push:
    branches:
      - main

jobs:
  update:
    name: Create or update test EAS build
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          registry-url: https://registry.npmjs.org
          scope: "@tendrel"
      - name: Install Dependencies
        env:
          BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun install --frozen-lockfile

      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Prepare bunfig for EAS
        run: bun scripts/prepare-bunfig.ts

      - name: Create test build
        uses: expo/expo-github-action/continuous-deploy-fingerprint@main
        with:
          profile: test
          branch: test

      - name: ğŸš€ Build app
        run: eas build --platform ios --profile test --non-interactive
